include: package:very_good_analysis/analysis_options.yaml

# These linter rules are only my personal preference.
linter:
  rules:
    avoid_positional_boolean_parameters: false
    avoid_catches_without_on_clauses: false
    constant_identifier_names: false
    lines_longer_than_80_chars: false
    sort_constructors_first: false
    sort_unnamed_constructors_first: false

formatter:
  page_width: 120

# Exclude generated files.
analyzer:
  exclude:
    - '**/*.freezed.dart'
    - '**/*.g.dart'
    - '**/l10n/*.dart'
    - '**/firebase_options.dart'
