name: schueler_app

packages:
  - apps/**
  - packages/**

scripts:
  setup:
    description: Copy the `analysis_options.yaml` file to the root of every package.
    exec: |
      cp $MELOS_ROOT_PATH/analysis_options.yaml .

  generate:
    description: Run build runner in the specified package(s).
    exec: dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      fileExists: build.yaml

  localize:
    description: Generate localization files for the specified package(s).
    exec: flutter gen-l10n
    packageFilters:
      fileExists: l10n.yaml
