name: sa_providers
description: Contains notifiers and providers to manage the application state.
version: 1.0.0

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies: 
  collection: ^1.19.1
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  sa_common: 1.0.0
  sa_data: 1.0.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0
