name: sa_data
description: Provides data layer functionality, i.e. models and repositories.
version: 0.0.1

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^5.6.4
  dartz: ^0.10.1
  fake_cloud_firestore: ^3.1.0
  firebase_core: ^3.12.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  sa_common: 0.0.1
  shared_preferences: ^2.5.2
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  json_serializable: ^6.9.4
  very_good_analysis: ^7.0.0
